#!/bin/bash

if [ -z $1 ]; then
  echo "Username not supplied, defaulting to bigboss."
  User=bigboss
else
  echo "Installing userfiles for user $1."
  USER=$1
fi

DIR=/home/$USER

cp bash_aliases $DIR/.bash_aliases

cp vimrc $DIR/.vimrc

mv $DIR/.bashrc $DIR/.bashrc.old

cat profile > $DIR/.bashrc
cat $DIR/.bashrc.old >> $DIR/.bashrc
